kind: pipeline
name: default

steps:
- name: build server
  image: plugins/docker
  settings:
    context: server
    tags:
      - 'server-latest'
    dockerfile: server/Dockerfile
    dry_run: true
- name: build ui  
  image: plugins/docker
  settings:
    context: ui
    tags:
      - 'ui-latest'
    dockerfile: ui/Dockerfile
    dry_run: true
