kind: pipeline
name: default

steps:
  - name: test
    image: compose:latest
    volumes:
    - name: docker_sock
      path: /var/run/docker.sock
    commands:
    - -f /drone/src/docker-compose-dev.yml up -abort-on-container-exit

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
