kind: pipeline
name: default

steps:
- name: build server
  image: plugins/docker
  settings:
    context: server
    tags: server-latest
- name: build ui  
  image: plugins/docker
  settings:
    context: ui
    tags: ui-latest
